/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.FrbProdutos;
import bean.FrbVendaprodutos;
import dao.FrbProdutosDAO;
import java.util.List;
import tools.Util;

/**
 *
 * @author u1845853
 */
public class JDlgFrbVendaProdutos extends javax.swing.JDialog {
    private JDlgFrbVendas jDlgFrbVendas;
    /**
     * Creates new form JDlgPedidosProdutos
     */
    public void setTelaAnterior(JDlgFrbVendas jDlgFrbVendas) {
        this.jDlgFrbVendas = jDlgFrbVendas;
    }
    public JDlgFrbVendaProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Pedidos produtos");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtFrbValorUnitario, jTxtFrbTotal);
        jTxtFrbQuantidade.setText("1");
        FrbProdutosDAO frbProdutosDAO = new FrbProdutosDAO();
        List listaVend = (List) frbProdutosDAO.listAll();
        for (Object object : listaVend) {
            jCboFrbProdutos.addItem((FrbProdutos) object);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCboFrbProdutos = new javax.swing.JComboBox<FrbProdutos>();
        jLabel2 = new javax.swing.JLabel();
        jTxtFrbQuantidade = new javax.swing.JTextField();
        jTxtFrbValorUnitario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtFrbTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtnFrbOk = new javax.swing.JButton();
        jBtnFrbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produtos");

        jCboFrbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboFrbProdutosActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        jTxtFrbQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtFrbQuantidadeKeyReleased(evt);
            }
        });

        jLabel3.setText("Valor Unitário");

        jTxtFrbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFrbTotalActionPerformed(evt);
            }
        });

        jLabel4.setText("Total");

        jBtnFrbOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnFrbOk.setText("OK");
        jBtnFrbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFrbOkActionPerformed(evt);
            }
        });

        jBtnFrbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnFrbCancelar.setText("Cancelar");
        jBtnFrbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFrbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jCboFrbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnFrbOk)
                                .addGap(40, 40, 40)
                                .addComponent(jBtnFrbCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTxtFrbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFrbValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFrbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFrbValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFrbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCboFrbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFrbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnFrbOk)
                    .addComponent(jBtnFrbCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFrbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrbOkActionPerformed
        // TODO add your handling code here:
        FrbVendaprodutos frbVendaprodutos = new FrbVendaprodutos();
        frbVendaprodutos.setFrbProdutos((FrbProdutos) jCboFrbProdutos.getSelectedItem());
        frbVendaprodutos.setFrbQuantidade(Util.strToInt(jTxtFrbQuantidade.getText()));
        frbVendaprodutos.setFrbPrecoUnitario(Util.strToDouble(jTxtFrbValorUnitario.getText()));
        jDlgFrbVendas.frbControllerVendaProdutos.addBean(frbVendaprodutos);
        setVisible(false);
    }//GEN-LAST:event_jBtnFrbOkActionPerformed

    private void jBtnFrbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrbCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnFrbCancelarActionPerformed

    private void jCboFrbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboFrbProdutosActionPerformed
        // TODO add your handling code here:
        FrbProdutos frbProdutos = (FrbProdutos) jCboFrbProdutos.getSelectedItem();
        jTxtFrbValorUnitario.setText(Util.doubleToString(frbProdutos.getFrbPreco()));
        int quant = Util.strToInt(jTxtFrbQuantidade.getText());
        jTxtFrbTotal.setText(Util.doubleToString(quant*frbProdutos.getFrbPreco()));
        
    
    }//GEN-LAST:event_jCboFrbProdutosActionPerformed

    private void jTxtFrbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFrbTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFrbTotalActionPerformed

    private void jTxtFrbQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFrbQuantidadeKeyReleased
        // TODO add your handling code here:
        if(!jTxtFrbQuantidade.getText().isEmpty()){
        FrbProdutos frbProdutos = (FrbProdutos) jCboFrbProdutos.getSelectedItem();
        int quant = Util.strToInt(jTxtFrbQuantidade.getText());
        jTxtFrbTotal.setText(Util.doubleToString(quant*frbProdutos.getFrbPreco()));
        }  else{ jTxtFrbTotal.setText("0");
        }
    }//GEN-LAST:event_jTxtFrbQuantidadeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFrbVendaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFrbVendaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFrbVendaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFrbVendaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFrbVendaProdutos dialog = new JDlgFrbVendaProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFrbCancelar;
    private javax.swing.JButton jBtnFrbOk;
    private javax.swing.JComboBox<FrbProdutos> jCboFrbProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtFrbQuantidade;
    private javax.swing.JTextField jTxtFrbTotal;
    private javax.swing.JTextField jTxtFrbValorUnitario;
    // End of variables declaration//GEN-END:variables
}
