/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author U42977829873
 */
public class JFrmFrbPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmFrbPrincipal() {
        initComponents();
        setTitle("Sistema de compras e Vendas");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuFrbCadastro = new javax.swing.JMenu();
        jMnuFrbClientes = new javax.swing.JMenuItem();
        jMnuFrbUsuarios = new javax.swing.JMenuItem();
        jMnuFrbProdutos = new javax.swing.JMenuItem();
        jMnuFrbVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuFrbSair = new javax.swing.JMenuItem();
        jMnuFrbMovimento = new javax.swing.JMenu();
        jMnuFrbVendas = new javax.swing.JMenuItem();
        jMnuFrbVendaProdutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuFrbCadastro.setText("Cadastros");

        jMnuFrbClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrbClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clients.png"))); // NOI18N
        jMnuFrbClientes.setText("Clientes");
        jMnuFrbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbClientesActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbClientes);

        jMnuFrbUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrbUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        jMnuFrbUsuarios.setText("Usuários");
        jMnuFrbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbUsuariosActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbUsuarios);

        jMnuFrbProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrbProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/network.png"))); // NOI18N
        jMnuFrbProdutos.setText("Produtos");
        jMnuFrbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbProdutosActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbProdutos);

        jMnuFrbVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrbVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administrator.png"))); // NOI18N
        jMnuFrbVendedor.setText("Vendedor");
        jMnuFrbVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbVendedorActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbVendedor);
        jMnuFrbCadastro.add(jSeparator1);

        jMnuFrbSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMnuFrbSair.setText("Sair");
        jMnuFrbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbSairActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbSair);

        jMenuBar1.add(jMnuFrbCadastro);

        jMnuFrbMovimento.setText("Movimento");

        jMnuFrbVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrbVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jMnuFrbVendas.setText("Vendas");
        jMnuFrbVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbVendasActionPerformed(evt);
            }
        });
        jMnuFrbMovimento.add(jMnuFrbVendas);

        jMnuFrbVendaProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrbVendaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accessibilty.png"))); // NOI18N
        jMnuFrbVendaProdutos.setText("VendaProdutos");
        jMnuFrbVendaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbVendaProdutosActionPerformed(evt);
            }
        });
        jMnuFrbMovimento.add(jMnuFrbVendaProdutos);

        jMenuBar1.add(jMnuFrbMovimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuFrbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbClientesActionPerformed
        // TODO add your handling code here:
        JDlgFrbClientes jDlgClientes = new JDlgFrbClientes(this,true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMnuFrbClientesActionPerformed

    private void jMnuFrbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgFrbUsuarios jDlgUsuarios = new JDlgFrbUsuarios(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuFrbUsuariosActionPerformed

    private void jMnuFrbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbProdutosActionPerformed
        // TODO add your handling code here:
        JDlgFrbProdutos jDlgProdutos = new JDlgFrbProdutos(this, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuFrbProdutosActionPerformed

    private void jMnuFrbVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbVendedorActionPerformed
        // TODO add your handling code here:
        JDlgFrbVendedor jDlgVendedor = new JDlgFrbVendedor(this, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuFrbVendedorActionPerformed

    private void jMnuFrbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbSairActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuFrbSairActionPerformed

    private void jMnuFrbVendaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbVendaProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuFrbVendaProdutosActionPerformed

    private void jMnuFrbVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbVendasActionPerformed
        // TODO add your handling code here:
        JDlgFrbVendas jDlgFrbVendas = new JDlgFrbVendas(this, true);
        jDlgFrbVendas.setVisible(true);
    }//GEN-LAST:event_jMnuFrbVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmFrbPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuFrbCadastro;
    private javax.swing.JMenuItem jMnuFrbClientes;
    private javax.swing.JMenu jMnuFrbMovimento;
    private javax.swing.JMenuItem jMnuFrbProdutos;
    private javax.swing.JMenuItem jMnuFrbSair;
    private javax.swing.JMenuItem jMnuFrbUsuarios;
    private javax.swing.JMenuItem jMnuFrbVendaProdutos;
    private javax.swing.JMenuItem jMnuFrbVendas;
    private javax.swing.JMenuItem jMnuFrbVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
