/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import tools.Util;

/**
 *
 * @author U42977829873
 */
public class JFrmFrbPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmFrbPrincipal() {
        initComponents();
        setTitle("Sistema de compras e Vendas");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBtnClientes = new javax.swing.JButton();
        jBtnProdutos = new javax.swing.JButton();
        jBtnVendas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnConsultaClientes = new javax.swing.JButton();
        jBtnConsultaProdutos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuFrbCadastro = new javax.swing.JMenu();
        jMnuFrbClientes = new javax.swing.JMenuItem();
        jMnuFrbUsuarios = new javax.swing.JMenuItem();
        jMnuFrbProdutos = new javax.swing.JMenuItem();
        jMnuFrbVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuFrbSair = new javax.swing.JMenuItem();
        jMnuFrbMovimento = new javax.swing.JMenu();
        jMnuFrbVendas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMnuFrbConsultaClientes = new javax.swing.JMenuItem();
        jMnuFrbConsultaProdutos = new javax.swing.JMenuItem();
        jMnuConsultaVendedor = new javax.swing.JMenuItem();
        jMnuConsultaVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jBtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jBtnClientes.setFocusable(false);
        jBtnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnClientes);

        jBtnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jBtnProdutos.setFocusable(false);
        jBtnProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnProdutos);

        jBtnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnVendas.setFocusable(false);
        jBtnVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendas);
        jToolBar1.add(jSeparator2);

        jBtnConsultaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clients.png"))); // NOI18N
        jBtnConsultaClientes.setFocusable(false);
        jBtnConsultaClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultaClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultaClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultaClientes);

        jBtnConsultaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jBtnConsultaProdutos.setFocusable(false);
        jBtnConsultaProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultaProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultaProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsultaProdutos);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tema.png"))); // NOI18N
        jButton3.setText("Alternar Tema");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMnuFrbCadastro.setText("Cadastros");

        jMnuFrbClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFrbClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clients.png"))); // NOI18N
        jMnuFrbClientes.setText("Clientes");
        jMnuFrbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbClientesActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbClientes);

        jMnuFrbUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFrbUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        jMnuFrbUsuarios.setText("Usuários");
        jMnuFrbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbUsuariosActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbUsuarios);

        jMnuFrbProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFrbProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/network.png"))); // NOI18N
        jMnuFrbProdutos.setText("Produtos");
        jMnuFrbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbProdutosActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbProdutos);

        jMnuFrbVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFrbVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administrator.png"))); // NOI18N
        jMnuFrbVendedor.setText("Vendedor");
        jMnuFrbVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbVendedorActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbVendedor);
        jMnuFrbCadastro.add(jSeparator1);

        jMnuFrbSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFrbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMnuFrbSair.setText("Sair");
        jMnuFrbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbSairActionPerformed(evt);
            }
        });
        jMnuFrbCadastro.add(jMnuFrbSair);

        jMenuBar1.add(jMnuFrbCadastro);

        jMnuFrbMovimento.setText("Movimento");

        jMnuFrbVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFrbVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jMnuFrbVendas.setText("Vendas");
        jMnuFrbVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbVendasActionPerformed(evt);
            }
        });
        jMnuFrbMovimento.add(jMnuFrbVendas);

        jMenuBar1.add(jMnuFrbMovimento);

        jMenu1.setText("Consultas");

        jMnuFrbConsultaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clients.png"))); // NOI18N
        jMnuFrbConsultaClientes.setText("Clientes");
        jMnuFrbConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbConsultaClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuFrbConsultaClientes);

        jMnuFrbConsultaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jMnuFrbConsultaProdutos.setText("Produtos");
        jMnuFrbConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrbConsultaProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuFrbConsultaProdutos);

        jMnuConsultaVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administrator.png"))); // NOI18N
        jMnuConsultaVendedor.setText("Vendedor");
        jMnuConsultaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultaVendedor);

        jMnuConsultaVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jMnuConsultaVendas.setText("Venda");
        jMnuConsultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaVendasActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuConsultaVendas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuFrbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbClientesActionPerformed
        // TODO add your handling code here:
        JDlgFrbClientes jDlgClientes = new JDlgFrbClientes(this,true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMnuFrbClientesActionPerformed

    private void jMnuFrbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgFrbUsuarios jDlgUsuarios = new JDlgFrbUsuarios(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuFrbUsuariosActionPerformed

    private void jMnuFrbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbProdutosActionPerformed
        // TODO add your handling code here:
        JDlgFrbProdutos jDlgProdutos = new JDlgFrbProdutos(this, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuFrbProdutosActionPerformed

    private void jMnuFrbVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbVendedorActionPerformed
        // TODO add your handling code here:
        JDlgFrbVendedor jDlgVendedor = new JDlgFrbVendedor(this, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuFrbVendedorActionPerformed

    private void jMnuFrbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbSairActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuFrbSairActionPerformed

    private void jMnuFrbVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbVendasActionPerformed
        // TODO add your handling code here:
        JDlgFrbVendas jDlgFrbVendas = new JDlgFrbVendas(this, true);
        jDlgFrbVendas.setVisible(true);
    }//GEN-LAST:event_jMnuFrbVendasActionPerformed

    private void jBtnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProdutosActionPerformed
        // TODO add your handling code here:
        jMnuFrbProdutosActionPerformed(null);
    }//GEN-LAST:event_jBtnProdutosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Util.alternarTema();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClientesActionPerformed
        // TODO add your handling code here:
        jMnuFrbClientesActionPerformed(null);
    }//GEN-LAST:event_jBtnClientesActionPerformed

    private void jBtnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendasActionPerformed
        // TODO add your handling code here:
        jMnuFrbVendasActionPerformed(null);
    }//GEN-LAST:event_jBtnVendasActionPerformed

    private void jMnuFrbConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbConsultaProdutosActionPerformed
        // TODO add your handling code here:
        JDlgFrbConsultaProdutos jDlgFrbConsultaProdutos = new JDlgFrbConsultaProdutos(this, true);
        jDlgFrbConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuFrbConsultaProdutosActionPerformed

    private void jMnuFrbConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrbConsultaClientesActionPerformed
        // TODO add your handling code here:
        JDlgFrbConsultaClientes jDlgFrbConsultaClientes = new JDlgFrbConsultaClientes(this, true);
        jDlgFrbConsultaClientes.setVisible(true);
    }//GEN-LAST:event_jMnuFrbConsultaClientesActionPerformed

    private void jBtnConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultaClientesActionPerformed
        // TODO add your handling code here:
        jMnuFrbConsultaClientesActionPerformed(null);
    }//GEN-LAST:event_jBtnConsultaClientesActionPerformed

    private void jBtnConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultaProdutosActionPerformed
        // TODO add your handling code here:
        jMnuFrbConsultaProdutosActionPerformed(null);
    }//GEN-LAST:event_jBtnConsultaProdutosActionPerformed

    private void jMnuConsultaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaVendedorActionPerformed
        // TODO add your handling code here:
        JDlgFrbConsultaVendedor jDlgFrbConsultaVendedor = new JDlgFrbConsultaVendedor(this, true);
        jDlgFrbConsultaVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaVendedorActionPerformed

    private void jMnuConsultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaVendasActionPerformed
        // TODO add your handling code here:
        JDlgFrbConsultaVendas jDlgFrbConsultaVendas = new JDlgFrbConsultaVendas(this, true);
        jDlgFrbConsultaVendas.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Util.aplicarTemaEscuroSimples();
                new JFrmFrbPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClientes;
    private javax.swing.JButton jBtnConsultaClientes;
    private javax.swing.JButton jBtnConsultaProdutos;
    private javax.swing.JButton jBtnProdutos;
    private javax.swing.JButton jBtnVendas;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuConsultaVendas;
    private javax.swing.JMenuItem jMnuConsultaVendedor;
    private javax.swing.JMenu jMnuFrbCadastro;
    private javax.swing.JMenuItem jMnuFrbClientes;
    private javax.swing.JMenuItem jMnuFrbConsultaClientes;
    private javax.swing.JMenuItem jMnuFrbConsultaProdutos;
    private javax.swing.JMenu jMnuFrbMovimento;
    private javax.swing.JMenuItem jMnuFrbProdutos;
    private javax.swing.JMenuItem jMnuFrbSair;
    private javax.swing.JMenuItem jMnuFrbUsuarios;
    private javax.swing.JMenuItem jMnuFrbVendas;
    private javax.swing.JMenuItem jMnuFrbVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
