/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FrbUsuariosDAO;
import tools.Util;

/**
 *
 * @author 70874542189
 */
public class JFrmFrbLogin extends javax.swing.JFrame {

    private int tentativas = 0;
    private int tentativasmax = 2;
    private FrbUsuariosDAO DAO = new FrbUsuariosDAO();
    
    /**
     * Creates new form JFrmFrbLogin
     */
    public JFrmFrbLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Login do Usuário:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtFrbApelido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPwdFrbSenha = new javax.swing.JPasswordField();
        jBtnFrbLogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Apelido");

        jTxtFrbApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFrbApelidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha");

        jBtnFrbLogar.setText("LOGAR");
        jBtnFrbLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFrbLogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtFrbApelido)
                    .addComponent(jBtnFrbLogar)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jPwdFrbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtFrbApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPwdFrbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnFrbLogar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFrbLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrbLogarActionPerformed

        String frbApelido = jTxtFrbApelido.getText().trim();
        String frbSenha = new String(jPwdFrbSenha.getPassword()).trim();

        if (frbApelido.isEmpty() || frbSenha.isEmpty()) {
            Util.mensagem("Preenche tudo seu cabecudo");
            return;
        }

        tentativas++;

        if (DAO.autenticar(frbApelido, frbSenha)) {
            Util.mensagem("Logado com total sucessidades");

            JFrmFrbPrincipal principal = new JFrmFrbPrincipal();
            principal.setVisible(true);
            this.dispose();
        } else {
            Util.mensagem("Usuário ou Senha incorretos!");

            if (tentativas >= tentativasmax) {
                Util.mensagem("Encerrando Sistema, você excedeu a quantidade de tentativas permitidas.");
                System.exit(0);
            }
        }
    }//GEN-LAST:event_jBtnFrbLogarActionPerformed

    private void jTxtFrbApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFrbApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFrbApelidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmFrbLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmFrbLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFrbLogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPwdFrbSenha;
    private javax.swing.JTextField jTxtFrbApelido;
    // End of variables declaration//GEN-END:variables
}
