/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pesquisar;

import controller.FrbControllerUsuarios;
import bean.FrbUsuarios;
import dao.FrbUsuariosDAO;
import java.util.List;
import view.JDlgFrbUsuarios;

/**
 *
 * @author 42977829873
 */
public class JDlgFrbUsuariosPesquisar extends javax.swing.JDialog {

    /**
     * Creates new form JDlgUsuariosPesquisar
     */
    private JDlgFrbUsuarios jDlgFrbUsuarios;
    FrbControllerUsuarios frbControllerUsuarios;

    public JDlgFrbUsuariosPesquisar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pesquisar Usuários");
        frbControllerUsuarios = new FrbControllerUsuarios();
        FrbUsuariosDAO frbUsuariosDAO = new FrbUsuariosDAO();
        List lista = (List) frbUsuariosDAO.listAll();
        frbControllerUsuarios.setList(lista);
        jTblFrbTabela.setModel(frbControllerUsuarios);
    }

    public void setTelaPai(JDlgFrbUsuarios jDlgFrbUsuarios) {
        this.jDlgFrbUsuarios = jDlgFrbUsuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanelFrbPainel = new javax.swing.JScrollPane();
        jTblFrbTabela = new javax.swing.JTable();
        jBtnFrbOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTblFrbTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelFrbPainel.setViewportView(jTblFrbTabela);

        jBtnFrbOK.setText("Ok");
        jBtnFrbOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnFrbOKMouseClicked(evt);
            }
        });
        jBtnFrbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFrbOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnFrbOK)
                    .addComponent(jScrollPanelFrbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPanelFrbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnFrbOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFrbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrbOKActionPerformed
        // TODO add your handling code here:
    int row = jTblFrbTabela.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Selecione um usuário na tabela!", 
            "Atenção", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    FrbUsuarios frbUsuarios = frbControllerUsuarios.getBean(row);
    jDlgFrbUsuarios.beanView(frbUsuarios);
    this.setVisible(false);
    }//GEN-LAST:event_jBtnFrbOKActionPerformed

    private void jBtnFrbOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnFrbOKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFrbOKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFrbUsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFrbUsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFrbUsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFrbUsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFrbUsuariosPesquisar dialog = new JDlgFrbUsuariosPesquisar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFrbOK;
    private javax.swing.JScrollPane jScrollPanelFrbPainel;
    private javax.swing.JTable jTblFrbTabela;
    // End of variables declaration//GEN-END:variables
}
