package bean;
// Generated Oct 13, 2025 10:55:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrbClientes generated by hbm2java
 */
@Entity
@Table(name="frb_clientes"
    ,catalog="db_filipe_barreto"
)
public class FrbClientes  implements java.io.Serializable {


     private int frbIdCliente;
     private String frbNome;
     private String frbCpf;
     private String frbRg;
     private String frbSexo;
     private Date frbDataNascimento;
     private String frbEmail;
     private String frbCep;
     private String frbEndereco;
     private String frbBairro;
     private String frbCidade;
     private String frbEstado;
     private String frbTelefoneCasa;
     private String frbCelular;
     private String frbSaborFavorito;
     private String frbAtivo;

    public FrbClientes() {
    }

	
    public FrbClientes(int frbIdCliente, String frbNome, String frbCpf, String frbRg, String frbSexo, String frbEmail, String frbCep, String frbEndereco, String frbBairro, String frbCidade, String frbEstado, String frbCelular, String frbSaborFavorito) {
        this.frbIdCliente = frbIdCliente;
        this.frbNome = frbNome;
        this.frbCpf = frbCpf;
        this.frbRg = frbRg;
        this.frbSexo = frbSexo;
        this.frbEmail = frbEmail;
        this.frbCep = frbCep;
        this.frbEndereco = frbEndereco;
        this.frbBairro = frbBairro;
        this.frbCidade = frbCidade;
        this.frbEstado = frbEstado;
        this.frbCelular = frbCelular;
        this.frbSaborFavorito = frbSaborFavorito;
    }
    public FrbClientes(int frbIdCliente, String frbNome, String frbCpf, String frbRg, String frbSexo, Date frbDataNascimento, String frbEmail, String frbCep, String frbEndereco, String frbBairro, String frbCidade, String frbEstado, String frbTelefoneCasa, String frbCelular, String frbSaborFavorito, String frbAtivo) {
       this.frbIdCliente = frbIdCliente;
       this.frbNome = frbNome;
       this.frbCpf = frbCpf;
       this.frbRg = frbRg;
       this.frbSexo = frbSexo;
       this.frbDataNascimento = frbDataNascimento;
       this.frbEmail = frbEmail;
       this.frbCep = frbCep;
       this.frbEndereco = frbEndereco;
       this.frbBairro = frbBairro;
       this.frbCidade = frbCidade;
       this.frbEstado = frbEstado;
       this.frbTelefoneCasa = frbTelefoneCasa;
       this.frbCelular = frbCelular;
       this.frbSaborFavorito = frbSaborFavorito;
       this.frbAtivo = frbAtivo;
    }
   
     @Id 

    
    @Column(name="frb_idCliente", unique=true, nullable=false)
    public int getFrbIdCliente() {
        return this.frbIdCliente;
    }
    
    public void setFrbIdCliente(int frbIdCliente) {
        this.frbIdCliente = frbIdCliente;
    }

    
    @Column(name="frb_nome", nullable=false, length=100)
    public String getFrbNome() {
        return this.frbNome;
    }
    
    public void setFrbNome(String frbNome) {
        this.frbNome = frbNome;
    }

    
    @Column(name="frb_cpf", nullable=false, length=14)
    public String getFrbCpf() {
        return this.frbCpf;
    }
    
    public void setFrbCpf(String frbCpf) {
        this.frbCpf = frbCpf;
    }

    
    @Column(name="frb_rg", nullable=false, length=13)
    public String getFrbRg() {
        return this.frbRg;
    }
    
    public void setFrbRg(String frbRg) {
        this.frbRg = frbRg;
    }

    
    @Column(name="frb_sexo", nullable=false, length=9)
    public String getFrbSexo() {
        return this.frbSexo;
    }
    
    public void setFrbSexo(String frbSexo) {
        this.frbSexo = frbSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="frb_dataNascimento", length=10)
    public Date getFrbDataNascimento() {
        return this.frbDataNascimento;
    }
    
    public void setFrbDataNascimento(Date frbDataNascimento) {
        this.frbDataNascimento = frbDataNascimento;
    }

    
    @Column(name="frb_email", nullable=false, length=50)
    public String getFrbEmail() {
        return this.frbEmail;
    }
    
    public void setFrbEmail(String frbEmail) {
        this.frbEmail = frbEmail;
    }

    
    @Column(name="frb_cep", nullable=false, length=9)
    public String getFrbCep() {
        return this.frbCep;
    }
    
    public void setFrbCep(String frbCep) {
        this.frbCep = frbCep;
    }

    
    @Column(name="frb_endereco", nullable=false, length=150)
    public String getFrbEndereco() {
        return this.frbEndereco;
    }
    
    public void setFrbEndereco(String frbEndereco) {
        this.frbEndereco = frbEndereco;
    }

    
    @Column(name="frb_bairro", nullable=false, length=50)
    public String getFrbBairro() {
        return this.frbBairro;
    }
    
    public void setFrbBairro(String frbBairro) {
        this.frbBairro = frbBairro;
    }

    
    @Column(name="frb_cidade", nullable=false, length=50)
    public String getFrbCidade() {
        return this.frbCidade;
    }
    
    public void setFrbCidade(String frbCidade) {
        this.frbCidade = frbCidade;
    }

    
    @Column(name="frb_estado", nullable=false, length=2)
    public String getFrbEstado() {
        return this.frbEstado;
    }
    
    public void setFrbEstado(String frbEstado) {
        this.frbEstado = frbEstado;
    }

    
    @Column(name="frb_telefoneCasa", length=15)
    public String getFrbTelefoneCasa() {
        return this.frbTelefoneCasa;
    }
    
    public void setFrbTelefoneCasa(String frbTelefoneCasa) {
        this.frbTelefoneCasa = frbTelefoneCasa;
    }

    
    @Column(name="frb_celular", nullable=false, length=15)
    public String getFrbCelular() {
        return this.frbCelular;
    }
    
    public void setFrbCelular(String frbCelular) {
        this.frbCelular = frbCelular;
    }

    
    @Column(name="frb_saborFavorito", nullable=false, length=30)
    public String getFrbSaborFavorito() {
        return this.frbSaborFavorito;
    }
    
    public void setFrbSaborFavorito(String frbSaborFavorito) {
        this.frbSaborFavorito = frbSaborFavorito;
    }

    
    @Column(name="frb_ativo", length=1)
    public String getFrbAtivo() {
        return this.frbAtivo;
    }
    
    public void setFrbAtivo(String frbAtivo) {
        this.frbAtivo = frbAtivo;
    }
    
    @Override
    public String toString(){
         return this.frbNome;
        
    }
    
    @Override
    public boolean equals(Object object){
        if (object instanceof FrbClientes){
            if (this.frbIdCliente == ((FrbClientes)object).frbIdCliente){
                return true;
            }
        }
        return false;
    }
}


