package bean;
// Generated Oct 13, 2025 10:55:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrbProdutos generated by hbm2java
 */
@Entity
@Table(name="frb_produtos"
    ,catalog="db_filipe_barreto"
)
public class FrbProdutos  implements java.io.Serializable {


     private int frbIdProduto;
     private String frbSabor;
     private String frbDescricao;
     private double frbPreco;
     private int frbEstoque;
     private int frbTamanho;
     private Date frbDataValidade;

    public FrbProdutos() {
    }

	
    public FrbProdutos(int frbIdProduto, String frbSabor, String frbDescricao, double frbPreco, int frbEstoque, int frbTamanho) {
        this.frbIdProduto = frbIdProduto;
        this.frbSabor = frbSabor;
        this.frbDescricao = frbDescricao;
        this.frbPreco = frbPreco;
        this.frbEstoque = frbEstoque;
        this.frbTamanho = frbTamanho;
    }
    public FrbProdutos(int frbIdProduto, String frbSabor, String frbDescricao, double frbPreco, int frbEstoque, int frbTamanho, Date frbDataValidade) {
       this.frbIdProduto = frbIdProduto;
       this.frbSabor = frbSabor;
       this.frbDescricao = frbDescricao;
       this.frbPreco = frbPreco;
       this.frbEstoque = frbEstoque;
       this.frbTamanho = frbTamanho;
       this.frbDataValidade = frbDataValidade;
    }
   
     @Id 

    
    @Column(name="frb_idProduto", unique=true, nullable=false)
    public int getFrbIdProduto() {
        return this.frbIdProduto;
    }
    
    public void setFrbIdProduto(int frbIdProduto) {
        this.frbIdProduto = frbIdProduto;
    }

    
    @Column(name="frb_sabor", nullable=false, length=50)
    public String getFrbSabor() {
        return this.frbSabor;
    }
    
    public void setFrbSabor(String frbSabor) {
        this.frbSabor = frbSabor;
    }

    
    @Column(name="frb_descricao", nullable=false, length=200)
    public String getFrbDescricao() {
        return this.frbDescricao;
    }
    
    public void setFrbDescricao(String frbDescricao) {
        this.frbDescricao = frbDescricao;
    }

    
    @Column(name="frb_preco", nullable=false, precision=10)
    public double getFrbPreco() {
        return this.frbPreco;
    }
    
    public void setFrbPreco(double frbPreco) {
        this.frbPreco = frbPreco;
    }

    
    @Column(name="frb_estoque", nullable=false)
    public int getFrbEstoque() {
        return this.frbEstoque;
    }
    
    public void setFrbEstoque(int frbEstoque) {
        this.frbEstoque = frbEstoque;
    }

    
    @Column(name="frb_tamanho", nullable=false)
    public int getFrbTamanho() {
        return this.frbTamanho;
    }
    
    public void setFrbTamanho(int frbTamanho) {
        this.frbTamanho = frbTamanho;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="frb_dataValidade", length=10)
    public Date getFrbDataValidade() {
        return this.frbDataValidade;
    }
    
    public void setFrbDataValidade(Date frbDataValidade) {
        this.frbDataValidade = frbDataValidade;
    }
    @Override
    public String toString(){
         return this.frbSabor;
        
    }
    
    @Override
    public boolean equals(Object object){
        if (object instanceof FrbProdutos){
            if (this.frbIdProduto == ((FrbProdutos)object).frbIdProduto){
                return true;
            }
        }
        return false;
    }

}


