package bean;
// Generated Oct 13, 2025 10:55:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrbUsuarios generated by hbm2java
 */
@Entity
@Table(name="frb_usuarios"
    ,catalog="db_filipe_barreto"
)
public class FrbUsuarios  implements java.io.Serializable {


     private int frbIdUsuario;
     private String frbNome;
     private String frbApelido;
     private String frbCpf;
     private Date frbDataNascimento;
     private String frbSenha;
     private int frbNivel;
     private String frbAtivo;

    public FrbUsuarios() {
    }

	
    public FrbUsuarios(int frbIdUsuario, String frbNome, String frbApelido, String frbCpf, String frbSenha, int frbNivel, String frbAtivo) {
        this.frbIdUsuario = frbIdUsuario;
        this.frbNome = frbNome;
        this.frbApelido = frbApelido;
        this.frbCpf = frbCpf;
        this.frbSenha = frbSenha;
        this.frbNivel = frbNivel;
        this.frbAtivo = frbAtivo;
    }
    public FrbUsuarios(int frbIdUsuario, String frbNome, String frbApelido, String frbCpf, Date frbDataNascimento, String frbSenha, int frbNivel, String frbAtivo) {
       this.frbIdUsuario = frbIdUsuario;
       this.frbNome = frbNome;
       this.frbApelido = frbApelido;
       this.frbCpf = frbCpf;
       this.frbDataNascimento = frbDataNascimento;
       this.frbSenha = frbSenha;
       this.frbNivel = frbNivel;
       this.frbAtivo = frbAtivo;
    }
   
     @Id 

    
    @Column(name="frb_idUsuario", unique=true, nullable=false)
    public int getFrbIdUsuario() {
        return this.frbIdUsuario;
    }
    
    public void setFrbIdUsuario(int frbIdUsuario) {
        this.frbIdUsuario = frbIdUsuario;
    }

    
    @Column(name="frb_nome", nullable=false, length=50)
    public String getFrbNome() {
        return this.frbNome;
    }
    
    public void setFrbNome(String frbNome) {
        this.frbNome = frbNome;
    }

    
    @Column(name="frb_apelido", nullable=false, length=25)
    public String getFrbApelido() {
        return this.frbApelido;
    }
    
    public void setFrbApelido(String frbApelido) {
        this.frbApelido = frbApelido;
    }

    
    @Column(name="frb_cpf", nullable=false, length=14)
    public String getFrbCpf() {
        return this.frbCpf;
    }
    
    public void setFrbCpf(String frbCpf) {
        this.frbCpf = frbCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="frb_dataNascimento", length=10)
    public Date getFrbDataNascimento() {
        return this.frbDataNascimento;
    }
    
    public void setFrbDataNascimento(Date frbDataNascimento) {
        this.frbDataNascimento = frbDataNascimento;
    }

    
    @Column(name="frb_senha", nullable=false, length=20)
    public String getFrbSenha() {
        return this.frbSenha;
    }
    
    public void setFrbSenha(String frbSenha) {
        this.frbSenha = frbSenha;
    }

    
    @Column(name="frb_nivel", nullable=false)
    public int getFrbNivel() {
        return this.frbNivel;
    }
    
    public void setFrbNivel(int frbNivel) {
        this.frbNivel = frbNivel;
    }

    
    @Column(name="frb_ativo", nullable=false, length=1)
    public String getFrbAtivo() {
        return this.frbAtivo;
    }
    
    public void setFrbAtivo(String frbAtivo) {
        this.frbAtivo = frbAtivo;
    }

}


