package bean;
// Generated Oct 13, 2025 10:55:48 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrbVendedor generated by hbm2java
 */
@Entity
@Table(name="frb_vendedor"
    ,catalog="db_filipe_barreto"
)
public class FrbVendedor  implements java.io.Serializable {


     private int frbIdVendedor;
     private String frbNome;
     private double frbComissao;
     private Date frbDataContrato;
     private String frbCpf;
     private String frbTelefone;
     private String frbEmail;

    public FrbVendedor() {
    }

	
    public FrbVendedor(int frbIdVendedor, String frbNome, double frbComissao, String frbCpf, String frbTelefone, String frbEmail) {
        this.frbIdVendedor = frbIdVendedor;
        this.frbNome = frbNome;
        this.frbComissao = frbComissao;
        this.frbCpf = frbCpf;
        this.frbTelefone = frbTelefone;
        this.frbEmail = frbEmail;
    }
    public FrbVendedor(int frbIdVendedor, String frbNome, double frbComissao, Date frbDataContrato, String frbCpf, String frbTelefone, String frbEmail, Set frbVendas) {
       this.frbIdVendedor = frbIdVendedor;
       this.frbNome = frbNome;
       this.frbComissao = frbComissao;
       this.frbDataContrato = frbDataContrato;
       this.frbCpf = frbCpf;
       this.frbTelefone = frbTelefone;
       this.frbEmail = frbEmail;
    }
   
     @Id 

    
    @Column(name="frb_idVendedor", unique=true, nullable=false)
    public int getFrbIdVendedor() {
        return this.frbIdVendedor;
    }
    
    public void setFrbIdVendedor(int frbIdVendedor) {
        this.frbIdVendedor = frbIdVendedor;
    }

    
    @Column(name="frb_nome", nullable=false, length=50)
    public String getFrbNome() {
        return this.frbNome;
    }
    
    public void setFrbNome(String frbNome) {
        this.frbNome = frbNome;
    }

    
    @Column(name="frb_comissao", nullable=false, precision=10)
    public double getFrbComissao() {
        return this.frbComissao;
    }
    
    public void setFrbComissao(double frbComissao) {
        this.frbComissao = frbComissao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="frb_dataContrato", length=10)
    public Date getFrbDataContrato() {
        return this.frbDataContrato;
    }
    
    public void setFrbDataContrato(Date frbDataContrato) {
        this.frbDataContrato = frbDataContrato;
    }

    
    @Column(name="frb_cpf", nullable=false, length=14)
    public String getFrbCpf() {
        return this.frbCpf;
    }
    
    public void setFrbCpf(String frbCpf) {
        this.frbCpf = frbCpf;
    }

    
    @Column(name="frb_telefone", nullable=false, length=15)
    public String getFrbTelefone() {
        return this.frbTelefone;
    }
    
    public void setFrbTelefone(String frbTelefone) {
        this.frbTelefone = frbTelefone;
    }

    
    @Column(name="frb_email", nullable=false, length=100)
    public String getFrbEmail() {
        return this.frbEmail;
    }
    
    public void setFrbEmail(String frbEmail) {
        this.frbEmail = frbEmail;
    }
    @Override
    public String toString(){
         return this.frbNome;
        
    }
    
    @Override
    public boolean equals(Object object){
        if (object instanceof FrbVendedor){
            if (this.frbIdVendedor == ((FrbVendedor)object).frbIdVendedor){
                return true;
            }
        }
        return false;
    }
}


