package bean;
// Generated Oct 13, 2025 10:55:48 PM by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrbVenda generated by hbm2java
 */
@Entity
@Table(name="frb_venda"
    ,catalog="db_filipe_barreto"
)
public class FrbVenda  implements java.io.Serializable {


     private int frbIdVenda;
     private FrbClientes frbClientes;
     private FrbVendedor frbVendedor;
     private Date frbDataVenda;
     private double frbValorTotal;
     private String frbStatusVenda;
     private String frbFormaPagamento;

    public FrbVenda() {
    }

	
    public FrbVenda(int frbIdVenda, FrbClientes frbClientes, FrbVendedor frbVendedor, Date frbDataVenda, double frbValorTotal, String frbStatusVenda, String frbFormaPagamento) {
        this.frbIdVenda = frbIdVenda;
        this.frbClientes = frbClientes;
        this.frbVendedor = frbVendedor;
        this.frbDataVenda = frbDataVenda;
        this.frbValorTotal = frbValorTotal;
        this.frbStatusVenda = frbStatusVenda;
        this.frbFormaPagamento = frbFormaPagamento;
    }

     @Id 

    
    @Column(name="frb_idVenda", unique=true, nullable=false)
    public int getFrbIdVenda() {
        return this.frbIdVenda;
    }
    
    public void setFrbIdVenda(int frbIdVenda) {
        this.frbIdVenda = frbIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="frb_fkCliente", nullable=false)
    public FrbClientes getFrbClientes() {
        return this.frbClientes;
    }
    
    public void setFrbClientes(FrbClientes frbClientes) {
        this.frbClientes = frbClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="frb_fkVendedor", nullable=false)
    public FrbVendedor getFrbVendedor() {
        return this.frbVendedor;
    }
    
    public void setFrbVendedor(FrbVendedor frbVendedor) {
        this.frbVendedor = frbVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="frb_dataVenda", nullable=false, length=10)
    public Date getFrbDataVenda() {
        return this.frbDataVenda;
    }
    
    public void setFrbDataVenda(Date frbDataVenda) {
        this.frbDataVenda = frbDataVenda;
    }

    
    @Column(name="frb_valorTotal", nullable=false, precision=10)
    public double getFrbValorTotal() {
        return this.frbValorTotal;
    }
    
    public void setFrbValorTotal(double frbValorTotal) {
        this.frbValorTotal = frbValorTotal;
    }

    
    @Column(name="frb_statusVenda", nullable=false, length=1)
    public String getFrbStatusVenda() {
        return this.frbStatusVenda;
    }
    
    public void setFrbStatusVenda(String frbStatusVenda) {
        this.frbStatusVenda = frbStatusVenda;
    }

    
    @Column(name="frb_formaPagamento", nullable=false, length=30)
    public String getFrbFormaPagamento() {
        return this.frbFormaPagamento;
    }
    
    public void setFrbFormaPagamento(String frbFormaPagamento) {
        this.frbFormaPagamento = frbFormaPagamento;
    }

}


