package bean;
// Generated Oct 13, 2025 10:55:48 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FrbVendaprodutos generated by hbm2java
 */
@Entity
@Table(name="frb_vendaprodutos"
    ,catalog="db_filipe_barreto"
)
public class FrbVendaprodutos  implements java.io.Serializable {


     private int frbIdVendaProduto;
     private FrbProdutos frbProdutos;
     private FrbVenda frbVenda;
     private int frbQuantidade;
     private double frbPrecoUnitario;

    public FrbVendaprodutos() {
    }

    public FrbVendaprodutos(int frbIdVendaProduto, FrbProdutos frbProdutos, FrbVenda frbVenda, int frbQuantidade, double frbPrecoUnitario) {
       this.frbIdVendaProduto = frbIdVendaProduto;
       this.frbProdutos = frbProdutos;
       this.frbVenda = frbVenda;
       this.frbQuantidade = frbQuantidade;
       this.frbPrecoUnitario = frbPrecoUnitario;
    }
   
     @Id 

    
    @Column(name="frb_idVendaProduto", unique=true, nullable=false)
    public int getFrbIdVendaProduto() {
        return this.frbIdVendaProduto;
    }
    
    public void setFrbIdVendaProduto(int frbIdVendaProduto) {
        this.frbIdVendaProduto = frbIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="frb_fkProduto", nullable=false)
    public FrbProdutos getFrbProdutos() {
        return this.frbProdutos;
    }
    
    public void setFrbProdutos(FrbProdutos frbProdutos) {
        this.frbProdutos = frbProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="frb_fkVenda", nullable=false)
    public FrbVenda getFrbVenda() {
        return this.frbVenda;
    }
    
    public void setFrbVenda(FrbVenda frbVenda) {
        this.frbVenda = frbVenda;
    }

    
    @Column(name="frb_quantidade", nullable=false)
    public int getFrbQuantidade() {
        return this.frbQuantidade;
    }
    
    public void setFrbQuantidade(int frbQuantidade) {
        this.frbQuantidade = frbQuantidade;
    }

    
    @Column(name="frb_precoUnitario", nullable=false, precision=10)
    public double getFrbPrecoUnitario() {
        return this.frbPrecoUnitario;
    }
    
    public void setFrbPrecoUnitario(double frbPrecoUnitario) {
        this.frbPrecoUnitario = frbPrecoUnitario;
    }

}


